### PR TITLE
Add Telegraf nightly dockerfiles

### PR DESCRIPTION
**Pull request by sspaink**
Add a new directory in the Telegraf docker folder that downloads from the nightly binaries.

### CODE REVIEW

**Comment by reimda** [comment]
@sspaink Are we adding these nightly dockerfiles just so people can build their own nightly images or were you thinking we would publish these on docker hub?

Nightly builds are alpha quality and I'm concerned that publishing a nightly image on docker hub would encourage people to use them in production, which isn't a good idea.

**Comment by sspaink** [comment]
I was thinking just to make it easier for people to build their own nightly images, publishing the nightly images probably isn't necessary and it would be better to avoid any confusion.

**Comment by sspaink** [comment]
@reimda and @powersj do you think this is ok to merge?

**Comment by reimda** [comment]
We made a change after you submitted this PR so telegraf runs as non-root user using su. We'll need to copy that change here.

Is the goal of nightly dockerfiles to make it easier for users to build their own images or so we can publish a new image on docker hub when a nightly build finishes?

**Comment by sspaink** [comment]
@reimda the goal is for users to build their own images, hoping this would just make it easier for them. Thanks for pointing out the need to use su, I've updated the dockerfiles to match.

**Review by reimda — APPROVED** [review]
Looks good!

**Pull request merged**
