### PR TITLE
update alpine images to 3.18

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by powersj** [comment]
+1 for telegraf images

**Comment by orgads** [comment]
ping

**Comment by powersj** [comment]
@bnpfeife @jeffreyssmith2nd same question here for influxdb and chronograph?

**Comment by jeffreyssmith2nd** [comment]
For influxdb and chronograf, we would only like to see the latest of each one updated. so 2.7, 1.11 and then 1.10 of chronograf. thanks for your help on this @orgads!

**Comment by orgads** [comment]
Done

**Review by jeffreyssmith2nd — APPROVED** [review]

**Review by powersj — APPROVED** [review]

**Comment by orgads** [comment]
Do you know why the alpine images for 2.7 were not updated?

**Comment by powersj** [comment]
@orgads - updates to the Official Docker Images are not automatic. We maintainers will need to push an update to [docker's official images](https://github.com/docker-library/official-images) to review, approve, and build. For telegraf we have a release tomorrow so that one will get our updated then.

**Comment by orgads** [comment]
Ok, thanks.

**Pull request merged**
