### PR TITLE
Upgrade base alpine image to 3.5

### PR DESCRIPTION
**Pull request by phedoreanu**

### CODE REVIEW

**Comment by jsternberg** [comment]
Can you upgrade this for all of the 1.1 images?

**Comment by phedoreanu** [comment]
Yes, sure. Done.

**Comment by jsternberg** [comment]
I think it's fine for nightly to use 3.5. It's a nightly of influxdb, not of alpine.

Can you update that last one and then I'll merge this?

**Comment by phedoreanu** [comment]
@jsternberg Which one is missing?

**Comment by jsternberg** [comment]
The one in `influxdb/nightly/alpine`. Can you also rebase this and update `kapacitor/1.2/alpine`?

**Comment by jsternberg** [comment]
I'm just going to merge this and modify those two myself. I need to update the telegraf images too so I might as well.

**Comment by jsternberg** [comment]
Sorry. It looks like `influxdb/nightly/alpine` was already updated and I missed it when looking at the diff. Thanks for your help!

**Pull request merged**
