### PR TITLE
update for Chronograf 1.8.10

### PR DESCRIPTION
**Pull request by timhallinflux**
and alpine-3.13

### CODE REVIEW

**Comment by russorat** [comment]
I'm not sure if we should worry about the circleci failures:
```
Executing busybox-1.31.1-r20.trigger
OK: 18 MiB in 30 packages
 ---> 400f24b67fb0
Step 6/9 : EXPOSE 8125/udp 8092/udp 8094
 ---> Running in d77efee1b238
 ---> 53c9921cd97b
Step 7/9 : COPY entrypoint.sh /entrypoint.sh
 ---> f01fbb3740ef
Step 8/9 : ENTRYPOINT /entrypoint.sh
 ---> Running in 3e96e6d3aff5
 ---> 9437acc337dc
Step 9/9 : CMD telegraf
 ---> Running in 4ab2df360777
 ---> f5219942758e
Successfully built f5219942758e
Successfully tagged telegraf:1.18-alpine
[2021/04/09 19:17:42 +0000] Failed to build the following images:
	chronograf:1.8
	chronograf:1.8-alpine

Exited with code exit status 2
CircleCI received exit code 2
```

**Comment by psteinbachs** [comment]
@codyshepherd Can you please work on the official docker image PR for this?  We'll need this for the 1.9.0 release.

**Comment by codyshepherd** [comment]
@psteinbachs Can you provide a little more context on what you mean? I investigated these build failures and they appear to be due to the fact that there are no signature files (.asc) in the s3 bucket as the build expects. Specifically, the build attempts to `curl` and `wget` the following URLS, respectively:

* `https://dl.influxdata.com/chronograf/releases/chronograf_1.8.10_amd64.deb.asc`
* `https://dl.influxdata.com/chronograf/releases/chronograf-1.8.10-static_linux_amd64.tar.gz.asc`

Neither of those files exist in the s3 bucket.

**Comment by timhallinflux** [comment]
@codyshepherd if we look at older versions of Chronograf, are those .asc files present in S3?  (older being prior to 1.8.8)

**Comment by cyounkins** [comment]
```
$ curl -s -w "%{http_code}\n" -o /dev/null 'https://dl.influxdata.com/chronograf/releases/chronograf_1.8.{6,7,8,9,10}_amd64.deb.asc'
200
200
200
404
404
$ curl -s -w "%{http_code}\n" -o /dev/null 'https://dl.influxdata.com/chronograf/releases/chronograf-1.8.{6,7,8,9,10}-static_linux_amd64.tar.gz.asc'
200
200
200
404
404
```

**Comment by cyounkins** [comment]
I see that the downloads page (https://portal.influxdata.com/downloads/) has a 1.8.10 image hosted on quay.io:
`docker pull quay.io/influxdb/chronograf:1.8.10`

It's unclear to me where the build files for that image are since they are not in this repo.

**Pull request closed without merging**
