### PR TITLE
Upgrading all instances of alpine:3.9 to 3.12

### PR DESCRIPTION
**Pull request by J0WI**
Fix https://github.com/influxdata/influxdata-docker/issues/366

### CODE REVIEW

**Comment by J0WI** [comment]
See https://github.com/tianon/pgp-happy-eyeballs to avoid random CI failures

**Comment by tianon** [comment]
This would be really helpful for things like a newer version of `smartmontools` -- any chance it could be considered? :pray:

**Comment by danielnelson** [comment]
I'm in favor of this change but I'd like to do it for Telegraf at the time we do a minor release: 1.x.0, but not retroactively.

**Comment by J0WI** [comment]
Alpine 3.9 will be EOL in a few months: https://wiki.alpinelinux.org/wiki/Releases

**Comment by J0WI** [comment]
:ping_pong: @jsternberg

**Pull request merged**
