### PR TITLE
Add lm_sensors package

### PR DESCRIPTION
**Pull request by ccmpbll**
The lm_sensors package is required for [inputs.sensors] to work. I was able to install the package after the container was up and running and and the following dependencies were also installed: readline, bash, sysfsutils

### CODE REVIEW

**Comment by jsternberg** [comment]
Is the same thing needed for the non-alpine image?

**Comment by ccmpbll** [comment]
I would say yes, but I haven't had a chance to test on that image yet.

**Comment by ccmpbll** [comment]
Any status updates on this? Have you guys had a chance to review it yet?

**Comment by ccmpbll** [comment]
@danielnelson lm-sensors package has been added to the Debian image and the tests passed once I realized the package name was different. (lm-sensors vs lm_sensors)

**Comment by danielnelson** [comment]
@ccmpbll Could you update the pull request to also target 1.7 Telegraf.  It is unlikely we will do another patch release of version <1.7.

**Comment by ccmpbll** [comment]
@danielnelson changes have been made for the 1.7 version for both Debian and Alpine images.

**Comment by danielnelson** [comment]
Can you either add it to 1.6 or remove from 1.5, so there is no gap and we can say things like lm-sensors support is in 1.x+.

**Comment by ccmpbll** [comment]
@danielnelson Changes made to both 1.6 images as well

**Comment by ccmpbll** [comment]
Anything else you need from me to get these changes merged?

**Pull request merged**
