### PR TITLE
Add default kapacitor configuration file at the default location

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by jsternberg** [comment]
@nathanielc while kapacitor doesn't support the default configuration file location yet, I want to include this as preparation.

Basically this just sets the default data directory locations.

**Comment by nathanielc** [comment]
For version 1.0 the config changed:

Add this bit
```
[storage]
  boltdb = "/var/lib/kapacitor/kapacitor.db"
```

And remove this section:

```
[task]
   dir = "/var/lib/kapacitor/tasks"
```

**Comment by jsternberg** [comment]
Is the tasks directory automatically discovered based on the `data_dir`?

**Comment by nathanielc** [comment]
The tasks dir is not longer used. All task data is stored in the generic `storage` backend.

**Comment by jsternberg** [comment]
Updated. It looks like the tasks section is still output with the default configuration file.

**Comment by nathanielc** [comment]
To be more specific: The task dir is officially deprecated. If it is found it will be used only to look for data in an old format and then migrate the data to the new `storage` backend. So for a default config in docker is doesn't need to be set and will not be used.

**Comment by nathanielc** [comment]
LGTM

**Pull request merged**
