### PR TITLE
Telegraf 1.9.0

### PR DESCRIPTION
**Pull request by danielnelson**
Remove 1.5, 1.6 and added 1.9.0-rc1

### CODE REVIEW

**Comment by mahmoudian1** [comment]
Hi, I am looking forward to use this for nginx_plus_api. @danielnelson please review when you have a chance.. Thanks.

**Comment by mahmoudian1** [comment]
I build the image and tested. It's working but I also get some error as below:
`telegraf_1        | 2018-11-06T19:49:00Z E! [inputs.nginx_plus_api]: Error in plugin: http://nginx:8080/api returned HTTP status 404 Not Found`

**Comment by jsternberg** [comment]
It looks like I was wrong and I don't have support for release candidate tagged versions in dockerlib (which is what I use to update official images).

I'll fix that up today so we can get docker images for the release candidates.

**Comment by danielnelson** [comment]
Thanks @jsternberg, I really appreciate all the help with the docker images.

**Comment by danielnelson** [comment]
Updated for 1.9.0 final release.

**Pull request merged**
