### PR TITLE
Add support for confd generated config file

### PR DESCRIPTION
**Pull request by blaggacao**
Confd files are usually generated by a sidekickcontainer, which volumes are shared with the main container. As either of:
- generating config files takes some time
- sidekick starts before main container
  can happen, this just loops over the config file folder and only contines when once available.

A very common pattern for confd managed config files.

### CODE REVIEW

**Comment by jsternberg** [comment]
A few comments on this. The first is why isn't it possible to launch the sidekick container before the telegraf container is launched? It seems like one is a dependency of the other and should be generated before the telegraf container is even generated.

The second is I don't like the indefinite waiting. I would rather telegraf fail to start if there is no config file rather than confusing the user into wondering why the container never starts and never has a log. For this to be merged, at a minimum, I would need there to be logging messages that it was waiting for a config file and it would need to not be indefinite waiting. I would still prefer that this behavior is handled outside of the docker image though if possible.

**Comment by blaggacao** [comment]
I think even if controlling the startup order of sidekicks (I think that's possible) signalling successful generation of a config file to the main container might be a different beast, so while waiting some seconds you have a very high probability that config was built.
I agree on timeout and logging.

However, this can be very easily integrated into a custom docker. I think the decision of integrating should depend on your strategy about how to manage dynamic configurations. I mean confd is just one option, although a common one.

**Comment by sparrc** [comment]
@blaggacao can you link to other projects that do this? I agree with @jsternberg, if the config file is a pre-requisite then it seems like the sidekick container should complete before launching the telegraf container,

Any configuration management system can do that for you.

**Comment by blaggacao** [comment]
Here we go, in this repo there is a wealth of examples of this pattern. https://github.com/rancher/catalog-dockerfiles/blob/master/elasticsearch/containers/0.5.0/elasticsearch-conf/run.sh

**Comment by sparrc** [comment]
@blaggacao I meant more general docker files, like the one we are dealing with here. It would make sense for dockerfiles within the rancher project to have this looping since it is specific to that problem.

**Comment by blaggacao** [comment]
Here is another one for an kubernetes docker file: https://github.com/fbrbovic/kubernetes-reverseproxy/blob/master/src/boot.sh

This is very characteristic for kv-configuration patterns, unless the very same application has it's own watcher routine.

So I would instead of "more general" formulate the following anatomy:
"Configuration Agnostic" vs "Distributed Configuration Ready" - well I just foolishly invented those terms in order to point out the argument.

**Comment by jsternberg** [comment]
I'm going to close this. This is specialized behavior and it's pretty easy for anyone who needs this to extend the base image and modify entrypoint.sh to wait for a configuration file.

**Pull request closed without merging**
