### PR TITLE
support arm64 architecture

### PR DESCRIPTION
**Pull request by longquan7**
I was build this dockerfile for arm64 architecture and successed, So I think we can add it to support arm64 architecture.

### CODE REVIEW

**Comment by jcberthon** [comment]
I can tell that it would be working on ARMv7 (32bit) as well if this line is added in each Dockerfile:

    armhf) ARCH='armhf';; \

I have tested it on my Raspberry Pi 2 that I can generate and run the telegraf image resp. container.

**Comment by longquan7** [comment]
@jcberthon  I was build on arm64V8 and it worked as well, I can add ARMv7(32bit ) in this pr

**Comment by jcberthon** [comment]
OK, then I need to wait for your PR to be merged then.

**Comment by jsternberg** [comment]
I've taken this change and created #138 to get it in there officially. An important part was I needed to modify the script that generates the library files for the official images repository to support multiple architectures.

Unfortunately, I do not own any of these architectures. I have a Raspberry Pi somewhere that I may try to configure sometime this weekend to test this on, but I'm not certain whether or not this change works. I know this may be asking a lot, but is there any chance the two of you could test that change for telegraf on whichever architectures you own and verify they work?

If it works for telegraf and I can get it merged into the official images correctly, then I will do the same for the other applications. Thanks for your work on this change.

**Comment by jcberthon** [comment]
I can do some of the testing. I have 2 Raspberry Pi 2 (ARMv7), one running Raspbian Stretch and the other Ubuntu 16.04.
I'm usually running telegraf inside a Docker container. With this in mind I can run the code on a armel (aka ARMv5) or armhf (aka ARMv7) "stack" depending on which base image I choose.
I'll start the testing tonight CEST. 
Thanks for your efforts supporting these architecture as well.

**Comment by longquan7** [comment]
@jcberthon It's good

**Comment by jsternberg** [comment]
Closed in favor of #138.

**Pull request closed without merging**
