### PR TITLE
Kapacitor 1.5.5

### PR DESCRIPTION
**Pull request by elohmeier**

### CODE REVIEW

**Comment by russorat** [comment]
@elohmeier thanks for the PR. Could you sign the CLA so i can merge? https://www.influxdata.com/legal/cla/

**Comment by elohmeier** [comment]
@russorat I did already sign the CLA. Please see my contributions to the Telegraf repo.

**Comment by nermolaev** [comment]
it's good fix, but working partially, and i don't know who can fix it :(
no necessary asc file for 1.5.5 in dl.influxdata.com, docker build will fail with next error:

> https://dl.influxdata.com/kapacitor/releases/kapacitor_1.5.5-1_amd64.deb.asc:
> 2020-05-22 09:02:56 ERROR 404: Not Found.

**Comment by hzliangbin** [comment]
any progress? 
`Successfully built 336da5c1a078
 
Successfully tagged telegraf:1.14-alpine
 
[2020/05/21 22:05:39 +0000] Failed to build the following images:
 
	kapacitor:1.5
 
	kapacitor:1.5-alpine
 
 `

**Comment by robcowart** [comment]
@hzliangbin Did you intend to tag someone else? I am not involved with this issue.

**Comment by hzliangbin** [comment]
> @hzliangbin Did you intend to tag someone else? I am not involved with this issue.

sorry..I didn't mean to.

**Comment by elohmeier** [comment]
Somebody pushed the change for 1.5.6, this change is not needed any more.

**Comment by elohmeier** [comment]
Related: #403

**Pull request closed without merging**
