### PR TITLE
Add enterprise clustering images for influxdb

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Comment by jsternberg** [comment]
@gunnaraasen @rossmcdonald @jackzampolin 

Initial start to the enterprise images. More discussion needed and the docs need to be done before this is merged, but this is a good starter point and one of you can take this PR, build the images, and try testing them out.

**Comment by jsternberg** [comment]
Updated the images to separate `influxdb-meta` into its own image and changed `influxdb:data` to `influxdb:enterprise`. Also modified the documentation to match.

**Comment by bbayani** [comment]
Can we have images with alpine base image too?
I am not able to find the installable in form of .tar.gz for influxdb-enterprise

**Comment by jsternberg** [comment]
An alpine version of the image will follow at some point, but merging original base images first is a priority.

**Pull request merged**
