### PR TITLE
Add ENV variable to set DB retention policy on container creation

### LINKED ISSUE #282: Retention Policy as a environment variable for influxdb
I would like to know if we can add a env variable as DURATION, REPLICA and SHARD_GRP_DURATION  for the retention policy.  I am currently using K8s with plain influxdb image and grafana. Its not simple to provide the retention policy as of now.

### LINKED ISSUE #407: Allow setting default Retention policy with Variable on Docker deployment
Having a variable such as DEFAULT_RETENTION_POLICY would make it a lot easier for deployments where storage is a concern.

### LINKED ISSUE #580: Why retention policy environment variable doesn't work?
I use _influxdb v1.7.11_ in a docker container. I read there is an env var in [hub.docker influxdb description](https://hub.docker.com/_/influxdb?tab=description) in order to set a retention policy on a database. However, it doesn't work!

> `DOCKER_INFLUXDB_INIT_RETENTION`: The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.

Here's a piece of my `docker-compose.yml`:

```
  influxdb:
    image: influxdb:1.7.11
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_USER=root
      - INFLUXDB_USER_PASSWORD=root
      - INFLUXDB_RETENTION_ENABLED=true
      - INFLUXDB_INIT_RETENTION=2h
      - DOCKER_INFLUXDB_INIT_RETENTION=2h
    volumes:
      - ./influxdb:/var/lib/influxdb
```

### PR DESCRIPTION
**Pull request by dbrennand**
Hello,

In this PR, I propose a new environment variable named `INFLUXDB_DB_RETENTION_POLICY`. I have tried to stick to current environment variable convention.

This PR resolves the opened issues (mentioned below) where users have asked for the functionality to specify a retention policy for an Influx database on initialisation of the container.

Resolves #282, resolves #407, resolved #580

I tested the new environment variable using the following commands:

```powershell
➜  1.8 git:(add-db-retention-policy-env) pwd

Path
----
..\influxdata-docker\influxdb\1.8

➜  1.8 git:(add-db-retention-policy-env) docker build --no-cache -t influxdbretention:testing .

➜  1.8 git:(add-db-retention-policy-env) ✗ docker run -d -p 127.0.0.1:8086:8086 --name influxtest `
>>      -e INFLUXDB_GRAPHITE_ENABLED=false `
>>      -e INFLUXDB_REPORTING_DISABLED=true `
>>      -e INFLUXDB_DB=twitter_users `
>>      -e INFLUXDB_USER=testing `
>>      -e INFLUXDB_USER_PASSWORD=testing123! `
>>      -e INFLUXDB_DB_RETENTION_POLICY='WITH DURATION 3d REPLICATION 1 SHARD DURATION 1h NAME liquid' `
>>      -v influxdb:/var/lib/influxdb `
>>      influxdbretention:testing

➜  1.8 git:(add-db-retention-policy-env) ✗ docker exec -it influxtest influx
Connected to http://localhost:8086 version 1.8.3
InfluxDB shell version: 1.8.3
> SHOW DATABASES
name: databases
----
twitter_users
_internal
> USE twitter_users
Using database twitter_users
> SHOW RETENTION POLICIES
name   duration shardGroupDuration replicaN default
----   -------- ------------------ -------- -------
liquid 72h0m0s  1h0m0s             1        true
> exit
```

As shown in the final command, the retention policy was set successfully on the initialised database.

If happy, the other `init-influxdb.sh` scripts will need this change also added.

Please let me know if there are any issues 😃

### CODE REVIEW

**Comment by agn-7** [comment]
Does this `INFLUXDB_DB_RETENTION_POLICY='WITH DURATION 3d REPLICATION 1 SHARD DURATION 1h NAME liquid'` environment variable work on *Influxdb v1.7.11*?

**Comment by dbrennand** [comment]
> Does this `INFLUXDB_DB_RETENTION_POLICY='WITH DURATION 3d REPLICATION 1 SHARD DURATION 1h NAME liquid'` environment variable work on _Influxdb v1.7.11_?

Hi @agn-7 

I haven't used InfluxDB in a while and I only tested with version 1.8 (which is what I was using at the time).

I just quickly pulled my old branch and tested the same change I made for 1.8 `init-influxdb.sh` with 1.7.

Results are below:

```bash
➜  1.7 git:(add-db-retention-policy-env) ✗ docker build -t influxdb-retention-policy:v1.7 .
[+] Building 4.1s (11/11) FINISHED
...
 => => naming to docker.io/library/influxdb-retention-policy:v1.7                                                                                                                                          
➜  1.7 git:(add-db-retention-policy-env) ✗ docker run --rm -d --name influxdb \
    -e INFLUXDB_GRAPHITE_ENABLED=false \
    -e INFLUXDB_REPORTING_DISABLED=true \
    -e INFLUXDB_DB=retention_test \
    -e INFLUXDB_USER=retention_test \
    -e INFLUXDB_USER_PASSWORD=testing123! \
    -e INFLUXDB_DB_RETENTION_POLICY='WITH DURATION 4d REPLICATION 1 SHARD DURATION 1h NAME liquid' \
    -v influxdb:/var/lib/influxdb \
    influxdb-retention-policy:v1.7
2b2cb1afbe50ae4747877d94229c0dc7fa75abfe98e50107131ef14c07a214fd
➜  1.7 git:(add-db-retention-policy-env) docker logs influxdb 2>&1 | grep 'service=query query="CREATE DATABASE'
ts=2022-02-19T11:19:26.288978Z lvl=info msg="Executing query" log_id=0ZlRAD0l000 service=query query="CREATE DATABASE retention_test WITH DURATION 96h0m0s REPLICATION 1 SHARD DURATION 1h0m0s NAME liquid"
➜  1.7 git:(add-db-retention-policy-env) docker exec -it influxdb influx
Connected to http://localhost:8086 version 1.7.11
InfluxDB shell version: 1.7.11
> SHOW DATABASES
name: databases
name
----
retention_test
_internal
> USE retention_test
Using database retention_test
> SHOW RETENTION POLICIES
name   duration shardGroupDuration replicaN default
----   -------- ------------------ -------- -------
liquid 96h0m0s  1h0m0s             1        true
> exit
```

**Comment by agn-7** [comment]
@dbrennand Thanks for your instant response.

But actually, I thought this pull request has been accepted and I can use it officially without building a new image from your branch.

**Comment by dbrennand** [comment]
Hi @agn-7 

Indeed, the PR hasn't been accepted yet :-( 

AFAIK, there is no way of creating the retention policy using environment variables when initalising the container on the offical images yet.

However, I don't think all hope is lost. I think you might be able to use an `.iql` [initalisation file](https://github.com/docker-library/docs/blob/master/influxdb/README.md#initialization-files) to set the retention policy.

See [here](https://github.com/influxdata/influxdata-docker/blob/master/influxdb/1.7/init-influxdb.sh#L117) in the `init-influxdb.sh` script. If a file ending in `.iql` is located in the directory `/docker-entrypoint-initdb.d/` inside the container, it will run:

```
influx -host 127.0.0.1 -port $INFLUXDB_INIT_PORT -execute <contents of your .iql file here>
```

**Comment by dbrennand** [comment]
Hi @agn-7 

So I just tested my thought above and it looks to be working with the offical `influxdb:1.7.11` container image.

setretention.iql file:

```
CREATE RETENTION POLICY "a_year" ON "retention_test" DURATION 52w REPLICATION 1
```

```
docker run --rm -d --name influxdb \
    -e INFLUXDB_GRAPHITE_ENABLED=false \
    -e INFLUXDB_REPORTING_DISABLED=true \
    -e INFLUXDB_DB=retention_test \
    -e INFLUXDB_USER=retention_test \
    -e INFLUXDB_USER_PASSWORD=testing123! \
    -v influxdb:/var/lib/influxdb \
    -v $(pwd)/setretention.iql:/docker-entrypoint-initdb.d/setretention.iql \
    influxdb:1.7.11
➜  1.7 git:(add-db-retention-policy-env) ✗ docker logs influxdb 2>&1 | grep 'running'
/init-influxdb.sh: running /docker-entrypoint-initdb.d/setretention.iql
➜  1.7 git:(add-db-retention-policy-env) ✗ docker logs influxdb 2>&1 | grep 'CREATE RETENTION POLICY'
ts=2022-02-19T17:01:05.176586Z lvl=info msg="Executing query" log_id=0Zljh~g0000 service=query query="CREATE RETENTION POLICY a_year ON retention_test DURATION 52w REPLICATION 1"
➜  1.7 git:(add-db-retention-policy-env) ✗ docker exec -it influxdb influx
Connected to http://localhost:8086 version 1.7.11
InfluxDB shell version: 1.7.11
> SHOW DATABASES
name: databases
name
----
retention_test
_internal
> USE retention_test
Using database retention_test
> SHOW RETENTION POLICIES
name    duration  shardGroupDuration replicaN default
----    --------  ------------------ -------- -------
autogen 0s        168h0m0s           1        true
a_year  8736h0m0s 168h0m0s           1        false
```

Hope this helps! 😃

**Comment by dbrennand** [comment]
You could also create the database and its retention policy using the `.iql` file:

createdbwithretention.iql:

```
CREATE DATABASE "test_db" WITH DURATION 3d REPLICATION 1 SHARD DURATION 1h NAME "retention_test"
```

Terminal:

> [!NOTE]
>
> The environment variable `INFLUXDB_DB` is removed in the `docker run` command as the DB is being initalised using the `.iql` file 🙂 

```bash
➜  1.7 git:(add-db-retention-policy-env) ✗ docker run --rm -d --name influxdb \
    -e INFLUXDB_GRAPHITE_ENABLED=false \
    -e INFLUXDB_REPORTING_DISABLED=true \
    -e INFLUXDB_USER=retention_test \
    -e INFLUXDB_USER_PASSWORD=testing123! \
    -v influxdb:/var/lib/influxdb \
    -v $(pwd)/createdbwithretention.iql:/docker-entrypoint-initdb.d/createdbwithretention.iql \
    influxdb:1.7.11
3e854b643783bfad099c34bbcb6cfaf0b25dde501593ab8d28aa23f907cfe25e
➜  1.7 git:(add-db-retention-policy-env) ✗ docker logs influxdb 2>&1 | grep 'running'
/init-influxdb.sh: running /docker-entrypoint-initdb.d/createdbwithretention.iql
➜  1.7 git:(add-db-retention-policy-env) ✗ docker logs influxdb 2>&1 | grep 'CREATE DATABASE'
ts=2022-02-19T17:12:08.640802Z lvl=info msg="Executing query" log_id=0ZlkLUzG000 service=query query="CREATE DATABASE test_db WITH DURATION 72h0m0s REPLICATION 1 SHARD DURATION 1h0m0s NAME retention_test"
➜  1.7 git:(add-db-retention-policy-env) ✗ docker exec -it influxdb influx
Connected to http://localhost:8086 version 1.7.11
InfluxDB shell version: 1.7.11
> SHOW DATABASES
name: databases
name
----
test_db
_internal
> USE test_db
Using database test_db
> SHOW RETENTION POLICIES
name           duration shardGroupDuration replicaN default
----           -------- ------------------ -------- -------
retention_test 72h0m0s  1h0m0s             1        true
> exit
```

**Comment by agn-7** [comment]
Thanks again for your great guidance.
It would be great if your valuable pull request will be approved as soon as possible.

**Review by Hipska — APPROVED** [review]

**Comment by Hipska** [comment]
Hi @dbrennand, thanks for this PR. Could you add the following in your initial description so the issues will be closed upon merging this?

> resolves #282, resolves #407, resolves #580

**Comment by dbrennand** [comment]
> Hi @dbrennand, thanks for this PR. Could you add the following in your initial description so the issues will be closed upon merging this?
> 
> > resolves #282, resolves #407, resolves #580

Hi @Hipska 

Thanks for PRing 👍🏻 

Should support be added for [influxdb/1.9/init-influxdb.sh](https://github.com/influxdata/influxdata-docker/blob/master/influxdb/1.9/init-influxdb.sh) as well?

**Comment by echtelerp** [comment]
I found an error in the init file that was on the PR: 
line 34 should be: WITH DURATION... otherwise it fails to start. 

line34: 		CREATE_DB_QUERY="CREATE DATABASE $INFLUXDB_DB **WITH DURATION** $INFLUXDB_DB_RETENTION_POLICY"

**Review by echtelerp — COMMENTED** [review]
line 31 should be: 
		CREATE_DB_QUERY="CREATE DATABASE $INFLUXDB_DB WITH DURATION $INFLUXDB_DB_RETENTION_POLICY"

**Comment by Hipska** [comment]
@dbrennand I would add it on every supported version indeed..

**Comment by dbrennand** [comment]
Hi @echtelerp

Usage of the environment variable `INFLUXDB_DB_RETENTION_POLICY` proposed in this PR is to include `WITH DURATION` in the string passed to it.

Usage example in my initial PR:

```
➜  1.8 git:(add-db-retention-policy-env) ✗ docker run -d -p 127.0.0.1:8086:8086 --name influxtest `
>>      -e INFLUXDB_GRAPHITE_ENABLED=false `
>>      -e INFLUXDB_REPORTING_DISABLED=true `
>>      -e INFLUXDB_DB=twitter_users `
>>      -e INFLUXDB_USER=testing `
>>      -e INFLUXDB_USER_PASSWORD=testing123! `
>>      -e INFLUXDB_DB_RETENTION_POLICY='WITH DURATION 3d REPLICATION 1 SHARD DURATION 1h NAME liquid' `
>>      -v influxdb:/var/lib/influxdb `
>>      influxdbretention:testing
````

This would be why Influx DB was not starting. 

This does highlight whether `WITH DURATION` should be included in the init script so the user does not have to provide it. Personally, I would argue against it based on the example query from the [documentation](https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#create-a-database-with-a-specific-retention-policy). Splitting the query into each section the `WITH DURATION` is part of the retention policy.

The create database part of the query:

> CREATE DATABASE "NOAA_water_database"

The retention policy part of the query:

> WITH DURATION 3d REPLICATION 1 SHARD DURATION 1h NAME "liquid"

What do you think? @agn-7 @Hipska  @echtelerp I want it to be as easy a possible for users 🙂

**Comment by agn-7** [comment]
@dbrennand In my opinion the proposed method is ok

**Comment by echtelerp** [comment]
I from a more user standpoint would split it to make it more accessible. 
Simple arguments are I think easier to use ;-) 
But both ways, if documented are fine for me.

**Comment by Hipska** [comment]
Actually, [the documentation](https://hub.docker.com/_/influxdb) for this var says it should only just contain a duration: `-e DOCKER_INFLUXDB_INIT_RETENTION=1w`

So this PR should reflect that and be compatible with it. Otherwise it can break setups for existing users..

**Comment by dbrennand** [comment]
> ~Actually, [the documentation](https://hub.docker.com/_/influxdb) for this var says it should only just contain a duration: `-e DOCKER_INFLUXDB_INIT_RETENTION=1w`~
> 
> ~So this PR should reflect that and be compatible with it. Otherwise it can break setups for existing users..~
> 
> Edit: I just saw this PR actually adds another var that's doing almost the same thing? Therefore I would ask to remove `resolves #580` from your initial description as that isn't correct. The already existing var seems to be broken and this PR is not solving that.

Hi @Hipska 

I'm pretty sure `DOCKER_INFLUXDB_INIT_RETENTION` is one of the new environment variables specific to InfluxDB docker image versions `2.x`. This PR was proposed over 2 years ago now, well before the InfluxDB `2.x` image was even available.

The proposed environment variable `INFLUXDB_DB_RETENTION_POLICY` in this PR conforms to the environment variable naming convention for `1.x` images [found here](https://github.com/docker-library/docs/blob/master/influxdb/README.md#database-initialization) and, was only meant to be for `1.x` images. If a user wants to use `2.x` images, they should use the new environment variable `DOCKER_INFLUXDB_INIT_RETENTION`.

Looking at issue #580, this PR would resolve it. The user is trying to use the new environment variable `DOCKER_INFLUXDB_INIT_RETENTION` (which is for 2.x images) with the 1.7.11 image. This PR would add the functionality which that user is looking for to the 1.7 image.

**Pull request closed without merging**
