### PR TITLE
fix for ping -i

### PR DESCRIPTION
**Pull request by gamkiller77**
added iputils to the top level so ping -i works.

for version 1.2.1

(i will update the 1.1 branch next.)

### CODE REVIEW

**Comment by jsternberg** [comment]
Can you do both of these changes in the same commit and then push to the same branch? Should be something like this:

```
$ git checkout patch-2
$ git cherry-pick patch-3
$ git reset HEAD~1
$ git commit -a --amend
$ git push -f origin patch-2
```

Replace `origin` with whatever you have as your remote name for your repository. I'll close the other issue so these two can be merged together.

**Comment by gamkiller77** [comment]
When i did tried the commit from my clone on my laptop i got permission problems that why i did the edits on the website.

**Comment by jsternberg** [comment]
I'll just merge the commits locally then and ensure you're still listed as the author. I think GitHub allows me to push to forks of projects I have commit access to.

**Comment by jsternberg** [comment]
@gamkiller77 I don't like to use the force push to other people's forks thing unless I'm given permission. Do I have permission to force push to your fork with those commits merged?

**Comment by gamkiller77** [comment]
@jsternberg yes you may force push.

**Pull request merged**
