### PR TITLE
Add support for all arm32v6, arm32v7, and arm64v8 in telegraf

### PR DESCRIPTION
**Pull request by jsternberg**
Thanks to @longquan7 for the original Dockerfiles and @jcberthon for the
follow up code to support 32-bit arm architectures.

### CODE REVIEW

**Comment by jcberthon** [comment]
Note that the base image `buildpack-deps:trusty-curl` is provided for several architecture thanks to the newly introduced "manifest" feature on Docker Hub. It however supports only the following list of architecture (see https://github.com/docker-library/official-images/blob/master/library/buildpack-deps) for the `trusty-curl`tag: `amd64, arm32v7, arm64v8, i386, ppc64le`

With my Raspberry Pi 2, I can test the arm32v7 architecture (aka armhf on Debian/Ubuntu). If I want to to try the arm32v5/v6 (aka armel on Debian/Ubuntu), I cannot use the base image from your Dockerfile as it isn't supported (see above). But I could do it using the following base image `buildpack-deps:stretch-curl`. This base image supports more architecture than the `ubuntu-curl` one, namely it supports `amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x`. Now thanks to a Docker "feature" ;-) (see this twitter thread https://twitter.com/tianon/status/909085407245082624) it currently picks up the armel variant on my Raspberry Pi instead of the armhf. Therefore by modifying the Dockerfile, I can in theory test `armel` architecture.

**Comment by jcberthon** [comment]
OK I got confused checking only the commit comment when you said arm32v6. I thought you meant `armel` (so running on a Raspberry Pi 1, or Zero). But checking the changes, you only added support for arm64 and armhf (which for me is arm32v7 only).

You could add supports for arm32v5 and arm32v6 (aka armel as far as I understood), by switching the base image to `buildpack-deps:stretch-curl` and adding the following line of code:

    armel) ARCH='armel';; \

I was able to successfully build the image with those 2 changes. I'm now going to test it.

**Comment by jsternberg** [comment]
To clarify, arm32v6 is armel? I'm not sure I want to change the base image for this change in particular. I'm definitely open to modifying the base image, I would just want to do it as part of a follow up change. So should I remove arm32v6 from the list of supported architectures?

That twitter thread also seems to indicate that the ARM support for choosing the correct architecture isn't quite working yet. Is that true?

**Comment by jcberthon** [comment]
I'm not sure I can answer your first question. To my understanding, armel is 32bit ARM with floating point emulation (because the CPU does not support floating point instructions), and that "armel" should work on ARMv5 and ARMv6. armhf is the same 32bit instructions plus hardware floating point, this should also correspond to ARMv7.

I understand that you do not want to change the base image within this PR. But I have already run telegraf on my 2 Raspberry Pis using the `xenial-curl` for more than 6 months now. And it is pretty robust. As I said in my previous post, I'm currently testing 2 images, one untouched from your branch and using armhf out of the box, it is working like a charm for the past hour. The other one, where I switched to the `stretch-curl` base image and it picked the armel architecture, it is running on my second Raspberry Pi 2, and it is also running well for the past hour.

As for the twitter thread. It only means that currently when an image which defines a manifest (and therefore can be pulled from different supported architecture) supports both armel and armhf, and that your client is armhf capable, docker picks up the armel variant none-the-less. It works, because the 32bit instructions set are compatible (same?), but every floating point operation is then emulated instead of using the hardware capabilities.

Anyway, currently with the picked image:tag for your base image, there is no armel support possible. That's because Ubuntu dropped support for armel and only provides armhf. Debian on the other side supports both (and I think the RHEL flavours do so as well). So docker picks up the correct architecture.

For the "new" PR to support armel, and move the base image to a newer one, you could wait for Docker to fix the "problem". In any case, it is non-blocking.

**Comment by jsternberg** [comment]
Hm, I haven't kept up much with Debian/Ubuntu releases so I didn't realize stretch was the current stable and xenial was the LTS for Ubuntu. It's likely lower risk to upgrade to those. I'm going to double check with others on the InfluxData team on Monday, but I'll push a commit with those for now.

I'm still concerned about the arm bug that causes it to use armel rather than armhf. From the sound of it, hardware floating point (if it's available) would be better for performance and I don't want to have that act as the default for platforms that have hardware floating point. So, until that bug is resolved, my current idea is to make the Dockerfile work with armel, but not upload it to the official images.

**Comment by jsternberg** [comment]
I've modified the Dockerfile and updated the manifest.json file so it targets architectures I described above. If you can try it, that would be very helpful.

**Comment by jcberthon** [comment]
Hi,

I have tested the build on the following host:
* Raspberry Pi 2 (armhf/arm32v7), Ubuntu 16.04.3 LTS, Docker CE 17.07 (edge)
* Raspberry Pi 2 (armhf/arm32v7), Raspbian Stretch, Docker CE 17.06.2 (stable)
* x86_64, Ubuntu 16.04.3 LTS, Docker CE 17.06.2 (stable)
* x86_64, Synology DSM 6.1, Docker 1.11.2

Docker is able to build the image successfully for the correct architecture. So it picks the armhf for my Raspberry Pis, and the amd64 for my Intel/AMD based machines.

I have run the image successfully as well. No error.

**Comment by jcberthon** [comment]
For the docker client problem when pulling the correct architecture for arm when an image is multi-arch, you are right, better wait for it to be fixed.

Anyway, as long as you use an Ubuntu-based image you can only support `amd64, arm32v7, arm64v8, i386, ppc64le` (so no arm32v6/armel). You would need to do the switch to Debian if you want to provide arm32v6/armel Docker images. Better wait for Docker to fix the problem and then evaluate the transition to Debian.

Alternative, you provide an "experimental" image for armel which is based on Debian Stretch (switch to the `stretch-curl` tag), and you tag it specifically. e.g. `telegraf:1.4.0-armel`. In order to avoid the Docker/arm bug, you should configure your CI to use Debian only for the armel build (I do not know how easy it is to do with your CI system). One way could be to use `ARG` before the `FROM`, something like (I only modified the 2 first lines):

```Dockerfile
ARG BASEOS=xenial
FROM buildpack-deps:${BASEOS}-curl

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends snmp && \
    rm -rf /var/lib/apt/lists/*

RUN set -ex && \
    for key in \
        05CE15085FC09D18E99EFB22684A14CF2582E0C5 ; \
    do \
        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" || \
        gpg --keyserver pgp.mit.edu --recv-keys "$key" || \
        gpg --keyserver keyserver.pgp.com --recv-keys "$key" ; \
    done

ENV TELEGRAF_VERSION 1.4.0
RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" && \
    case "${dpkgArch##*-}" in \
      amd64) ARCH='amd64';; \
      arm64) ARCH='arm64';; \
      armhf) ARCH='armhf';; \
      armel) ARCH='armel';; \
      *)     echo "Unsupported architecture: ${dpkgArch}"; exit 1;; \
    esac && \
    wget -q https://dl.influxdata.com/telegraf/releases/telegraf_${TELEGRAF_VERSION}-1_${ARCH}.deb.asc && \
    wget -q https://dl.influxdata.com/telegraf/releases/telegraf_${TELEGRAF_VERSION}-1_${ARCH}.deb && \
    gpg --batch --verify telegraf_${TELEGRAF_VERSION}-1_${ARCH}.deb.asc telegraf_${TELEGRAF_VERSION}-1_${ARCH}.deb && \
    dpkg -i telegraf_${TELEGRAF_VERSION}-1_${ARCH}.deb && \
    rm -f telegraf_${TELEGRAF_VERSION}-1_${ARCH}.deb*

EXPOSE 8125/udp 8092/udp 8094

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["telegraf"]
```

And you only modify `BASEOS` to `stretch` on the `armel` architecture in your CI (something like `docker build --build-arg BASEOS=stretch -t telegraf:1.4.0-armel .`)

**Comment by jsternberg** [comment]
I'll try seeing if the telegraf image will work on stretch. There was some weird issue with it at some point that meant it couldn't related to installing the systemd files (which are still installed as part of debian even if they are not used) that caused us to use ubuntu. That might not exist anymore.

**Comment by jsternberg** [comment]
The image appears to work on stretch, but it also appeared to work on jessie. I have no idea if we fixed something with the packaging at some point or something else happened, but I'm switching telegraf to stretch so it will eventually be consistent with the rest of the images. That way, armel should build perfectly fine.

We're not going to upload armel until the bug mentioned above is fixed, but it will allow people to more easily build their own images using the same Dockerfile and they can then upload it to their own location.

**Comment by longquan7** [comment]
I'm very happy to learned that this image can be support arm64

**Pull request merged**
